CREATE TABLE SYS_USER
(
	ID					SERIAL NOT NULL PRIMARY KEY,

	FIRST_NAME			VARCHAR(250) NOT NULL,
	LAST_NAME		    VARCHAR(250) NOT NULL,
	MIDDLE_NAME			VARCHAR(259) NOT NULL,
	
	DOCUMENT_TYPE_ID	INT NOT NULL,
	DOC_SERIA_NUMBER	VARCHAR(50) NOT NULL,
	
	PASSWORD_HASH		VARCHAR(250),
	PASSWORD_SALT		VARCHAR(250),
	EMAIL_ADDRESS		VARCHAR(50),

	STATE_ID			INT NOT NULL,

	CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			INT,
	MODIFIED_AT			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			INT,
	
	CONSTRAINT FK_DOCUMENT_TYPE_ID
		FOREIGN KEY (DOCUMENT_TYPE_ID) 
			REFERENCES ENUM_DOCUMENT_TYPE (ID),
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)	
);

CREATE INDEX SYS_USER_INDEX__STATE_ID
	ON SYS_USER (STATE_ID);

CREATE UNIQUE INDEX SYS_USER_INDEX_FIRST_NAME
	ON SYS_USER(FIRST_NAME);
	
CREATE UNIQUE INDEX SYS_USER_DOC_SERIA_NUMBER
	ON SYS_USER (DOC_SERIA_NUMBER)
		WHERE DOC_SERIA_NUMBER IS NOT NULL;