CREATE TABLE USER_WALLET(
    ID INT NOT NULL PRIMARY KEY,
    UNIQUE_CODE VARCHAR(12) NOT NULL,

    USER_ID  INT NOT NULL,
    AMOUNT DECIMAL DEFAULT 0,

    STATE_ID INT NOT NULL,
    CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),
    CONSTRAINT FK_USER_ID  
		FOREIGN KEY (USER_ID)
			REFERENCES SYS_USER (ID)
);