CREATE TABLE ENUM_STATE
(
	ID INT NOT NULL PRIMARY KEY,

	ORDER_CODE VARCHAR(5),
	SHORT_NAME	VARCHAR(250),
	FULL_NAME	VARCHAR(500),
	
	CREATED_AT	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);
INSERT INTO ENUM_STATE (ID, SHORT_NAME, FULL_NAME) 
VALUES (1,N'?',N'?????'),(2,N'?',N'??????');
CREATE TABLE ENUM_DOCUMENT_TYPE
(
	ID				INT NOT NULL PRIMARY KEY,

	ORDER_CODE		VARCHAR(50),
	SHORT_NAME		VARCHAR(250) NOT NULL,
	FULL_NAME		VARCHAR(250) NOT NULL,
	
	STATE_ID		INT NOT NULL,
	
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)	
);
INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (1,'1','???????','???????',1);
INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (2,'2','ID ?????','ID ?????',1);
INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (3,'3','Tug`ilganlik haqida guvohnoma','Tug`ilganlik haqida guvohnoma',1);
INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (4,'4','Chet el hujjati','Chet el hujjati',1);

CREATE TABLE SYS_USER
(
	ID					SERIAL NOT NULL PRIMARY KEY,

	FIRST_NAME			VARCHAR(250) NOT NULL,
	LAST_NAME		    VARCHAR(250) NOT NULL,
	MIDDLE_NAME			VARCHAR(259) NOT NULL,
	
	DOCUMENT_TYPE_ID	INT NOT NULL,
	DOC_SERIA_NUMBER	VARCHAR(50) NOT NULL,
	
	PASSWORD_HASH		VARCHAR(250),
	PASSWORD_SALT		VARCHAR(250),
	EMAIL_ADDRESS		VARCHAR(50),

	STATE_ID			INT NOT NULL,

	CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			INT,
	MODIFIED_AT			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			INT,
	
	CONSTRAINT FK_DOCUMENT_TYPE_ID
		FOREIGN KEY (DOCUMENT_TYPE_ID) 
			REFERENCES ENUM_DOCUMENT_TYPE (ID),
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)	
);

CREATE INDEX SYS_USER_INDEX__STATE_ID
	ON SYS_USER (STATE_ID);

CREATE UNIQUE INDEX SYS_USER_INDEX_FIRST_NAME
	ON SYS_USER(FIRST_NAME);
	
CREATE UNIQUE INDEX SYS_USER_DOC_SERIA_NUMBER
	ON SYS_USER (DOC_SERIA_NUMBER)
		WHERE DOC_SERIA_NUMBER IS NOT NULL;
		
INSERT INTO SYS_USER 
(FIRST_NAME, LAST_NAME, MIDDLE_NAME,DOCUMENT_TYPE_ID,DOC_SERIA_NUMBER,PASSWORD_HASH,PASSWORD_SALT,EMAIL_ADDRESS, state_id)
VALUES(
	N'BKEHZOD', 
	N'ALIMOV', 
	N'JOLOLITDINOVICH',
	(SELECT ID FROM ENUM_DOCUMENT_TYPE WHERE ID=2), 
	N'AA123456',
	'',
	'',
	N'admin@gmail.com',
	(SELECT ID FROM ENUM_STATE WHERE ID=1)
);
CREATE TABLE USER_WALLET(
    ID INT NOT NULL PRIMARY KEY,
    UNIQUE_CODE VARCHAR(12) NOT NULL,

    USER_ID  INT NOT NULL,
    AMOUNT DECIMAL DEFAULT 0,

    STATE_ID INT NOT NULL,
    CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),
    CONSTRAINT FK_USER_ID  
		FOREIGN KEY (USER_ID)
			REFERENCES SYS_USER (ID)
);
CREATE TABLE SYS_USER_WALLET_TURNOVOR
(
    ID BIGSERIAL NOT NULL,
    ON_DATE DATE NOT NULL,
    IS_DEBIT boolean,
    AMOUNT DECIMAL,
    USER_ID SERIAL NOT NULL,
    WALLET_ID INT NOT NULL,

    CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_USER_ID
		FOREIGN KEY (USER_ID)
			REFERENCES SYS_USER (ID),
 
	CONSTRAINT FK_WALLET_ID
		FOREIGN KEY (WALLET_ID)
			REFERENCES USER_WALLET (ID)
);